package com.ayutaki.chinjufumod.main;

import net.minecraftforge.fml.common.ModMetadata;

public class ChinjufuModInfoCore {

	public static void registerInfo(ModMetadata meta) {
		meta.modId = Reference.MOD_ID;
		meta.name = Reference.MOD_NAME;
		meta.description = "This is 'KantaiCollection' Fan Mod. KantaiCollection(DMM GAMES) http://www.dmm.com/netgame/feature/kancolle.html";
		meta.version = Reference.MOD_VERSION;
		meta.url = "https://minecraft.curseforge.com/projects/chinjufumod ChinjufuMod_wiki http://chinjufumod.wicurio.com/ My Blog http://ch.nicovideo.jp/ayutaki_s   Modding Tutorial https://ayutakimm.wp-x.jp/universal-en/contents-tree-en/";
		meta.authorList.add("Ayutaki Shou");
		meta.credits = "Thank you to those who are publishing MOD source code and those who upload maiking MOD videos.  I used SE on these sites. 効果音ラボ, On-Jin and niconi commons.";
		meta.logoFile = "";
		meta.autogenerated = false;
	}

}
